version: '3.10'

services:
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "${PWD}/.postgres-data:/var/lib/postgresql/data"
  